# Robot kinematics
WHEEL_DIAMETER_MM = 90.5
WHEELBASE_MM = 388
ENCODER_RESOLUTION = 4192
MAX_ANGULAR_VELOCITY_RPM = 76

# TODO verify and use directions
class SpeedDircetion:
    CLOCKWISE = 1
    COUNTERCLOCKWISE = -1

RIGHT_MOTOR_SPEED_DIR = SpeedDircetion.CLOCKWISE
LEFT_MOTOR_SPEED_DIR = SpeedDircetion.COUNTERCLOCKWISE


# Pins
RIGHT_MOTOR_PIN_A = 17
RIGHT_MOTOR_PIN_B = 27
LEFT_MOTOR_PIN_A = 23
LEFT_MOTOR_PIN_B = 22

# PID controller parameters
PID_KP = 1
PID_KI = 0
PID_KD = 0
PID_WINDUP_GUARD = 20
